@startuml

class Buiness {
 - name: string 
 - city: string
 - hotels: Hotel[]
}

class Hotel {
  - nom: string 
  - address: string 
  - tel : int 
  - email: string
  - rooms: Room[]
}


class Client{
}

class Booking{
}

class Room {
  - numero: int
  - price: float 
  - type : string
  - floor: int 
  - prestation: string 


}

class Option {
  - nom: string 
  - priceSup: float 
}

' 17 Une entreprise gère des hôtels. 
' Des clients peuvent réserver des chambres dans ces hôtels. 
' Une réservation ne peut porter que sur une seule chambre. 
' Des prestations supplémentaires (petit déjeuner, réveil par l’accueil, encas nocturne) peuvent compléter la mise à disposition d’une chambre. 
' Ces prestations peuvent être prévues lors de la réservation ou ultérieurement. 
' Une chambre est équipé ou non de différentes options (lit simple / double, micro-onde, lit enfant, baignoire de type balnéo, etc) Les associations doivent être nommées et les cardinalités précisées.

' * : có nghĩa là 0, 1 hoặc rất nhiều = 0..*
Buiness "1" -- "1..*" Hotel
Hotel "1" -- "1..*" Room 
Client "1" -- "0..*" Booking
Room "1" -- "0..*" Booking 
Room "0..*" -- "0..*" Option 


@enduml